import Compound from "@/Components/Compound/Compound";
import Contribution from "@/Components/Contribute/Contribution";
import Interest from "@/Components/Interest/Interest";
import Investment from "@/Components/investment/Investment";
import Results from "@/Components/Results/results";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Compound Interest Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-4xl flex justify-center m-5 font-extrabold">
          Compound Interest Calculator
        </h1>
        <h2 className="flex text-2xl font-semibold justify-center mb-5">
          Use the compound interest calculator to discover the power of compund
          interest and see how far your money can take you.
        </h2>

        <div className="flex-col">
          <Investment />
          <Contribution />
          <Interest />
          <Compound />
          <Results />
        </div>
      </main>
    </>
  );
}
