import Compound from "@/Components/Compound/Compound";
import Contribution from "@/Components/Contribute/Contribution";
import Interest from "@/Components/Interest/Interest";
import Investment from "@/Components/investment/Investment";
import Results from "@/Components/Results/results";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Compound Interest Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="header">Compound Interest Calculator</div>
        <div className="container">
          <Investment />
          <Contribution />
          <Interest />
          <Compound />
          <Results />
        </div>
      </main>
    </>
  );
}
