import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div>Initial Investment</div>
          <div>
            <div>monthly contribution</div>
            <div>length of Time in Years</div>
          </div>
          <div>
            <div>Estimated Interest Rate</div>
            <div>Estimated Rate Variance Range</div>
          </div>
          <div>Compound</div>
        </div>
      </main>
    </>
  );
}
